### ISSUE TITLE
UserUpdateRequest unique user clash

### ISSUE THREAD

**Issue by Nickdewolf** [Rndwiga/mnara#1]
At the moment it is not possible to update name/mail/password of a user because the validation rules are including the user that is being updated.

From what I see in the file, the solution is present (altough in the comments) inside the file:

Old situation:
`'name' => 'required|max:255|unique:users',`
`'email' => 'required|email|unique:users',`

My current solution:
`name' => 'required|max:255|unique:users,name,'.$this->user,`
`'email' => 'required|email|unique:users,email,'.$this->user,`

Am I missing a nicer solution (I dislike editing vendor files directly/forking and risking that I get out of sync with this nice repository) or is this a legit bug?

**Comment by Rndwiga** [comment]
Hi @Nickdewolf ,
Yes, it was not possible to update another user info as you pointed out. I have fixed in commit  #34d911b. However, since i have been working on improving the package over the past one month. I am pushing a minor release that will have the improvements and the fix.

**Comment by Nickdewolf** [comment]
Awesome!

**Comment by Rndwiga** [comment]
@Nickdewolf check out the release
